VERSION: 2
MODEL:
#  WEIGHTS: "https://dl.fbaipublicfiles.com/detectron2/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x/137849600/model_final_f10217.pkl"
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  META_ARCHITECTURE: "GeneralizedRCNN"
  MASK_ON: True

  BACKBONE:
    NAME: "build_resnet_fpn_backbone"
  RESNETS:
    OUT_FEATURES: ["res2", "res3", "res4", "res5"]
    DEPTH: 50

  FPN:
    IN_FEATURES: ["res2", "res3", "res4", "res5"]

  ANCHOR_GENERATOR:
    SIZES: [[32], [64], [128], [256], [512]]  # One size for each in feature map
    ASPECT_RATIOS: [[0.5, 1.0, 2.0]]  # Three aspect ratios (same for all in feature maps)
  RPN:
    IN_FEATURES: ["p2", "p3", "p4", "p5", "p6"]
    PRE_NMS_TOPK_TRAIN: 2000  # Per FPN level
    PRE_NMS_TOPK_TEST: 1000  # Per FPN level
    POST_NMS_TOPK_TRAIN: 1000
    POST_NMS_TOPK_TEST: 1000

  ROI_HEADS:
    NAME: "StandardROIHeads"
    IN_FEATURES: ["p2", "p3", "p4", "p5"]
    NUM_CLASSES: 7

  ROI_BOX_HEAD:
    NAME: "FastRCNNConvFCHead"
    NUM_FC: 2
    FC_DIM: 1024
    NORM: ""
    POOLER_RESOLUTION: 7
    CLS_AGNOSTIC_BBOX_REG: False

  ROI_MASK_HEAD:
    NAME: "BCNetConvGCNHead"
    NUM_CONV: 4
    CONV_DIM: 256
    POOLER_RESOLUTION: 14
    NORM: "BN"
    CLS_AGNOSTIC_MASK: True

DATASETS:
  TRAIN:
  - kins_dataset_train
  TEST:
  - kins_dataset_val

SOLVER:
  IMS_PER_BATCH: 1
  BASE_LR: 0.0025
  STEPS: (30000, 40000)
  MAX_ITER: 48000
  CHECKPOINT_PERIOD: 1000
TEST:
  EVAL_PERIOD: 1000

INPUT:
  MIN_SIZE_TRAIN: (800,)
  MAX_SIZE_TRAIN: 3000
  MIN_SIZE_TEST: 800
  MAX_SIZE_TEST: 3000

OUTPUT_DIR: output_data/train_outputs/kins/kinscscscs/

SEED: 1
